/* Local holographic renderer: lit surfaces, Fresnel shells and a four-pass bloom compositor. */
(()=>{'use strict';const G=window.Village3D;
 const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const l=Math.hypot(...a)||1;return a.map(v=>v/l)};
 function look(eye,target){const z=norm(sub(eye,target)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1])}
 function ortho(w,h){return new Float32Array([1/w,0,0,0,0,1/h,0,0,0,0,-2/240,0,0,0,-1,1])}
 class Engine{
  constructor(canvas){this.canvas=canvas;const gl=canvas.getContext('webgl',{antialias:false,alpha:false,powerPreference:'default'});if(!gl)throw Error('3D 표시 불가');this.gl=gl;this.resources=[];this.camera={angle:.035,zoom:.92,x:0,y:8,z:3};this.target={...this.camera};this.parallax={x:0,y:0};this.aim={x:0,y:0};this.width=1;this.height=1;this.vp=new Float32Array(16);this.buffers=[];
   this.program=this.compile(`attribute vec3 p;attribute vec3 n;attribute vec3 c;uniform mat4 vp;uniform mat4 m;varying vec3 rgb;varying vec3 normal;varying vec3 world;void main(){normal=normalize(mat3(m)*n);world=(m*vec4(p,1.)).xyz;rgb=c;gl_Position=vp*vec4(world,1.);}`,`precision mediump float;varying vec3 rgb;varying vec3 normal;varying vec3 world;uniform vec3 eye;uniform float emission;uniform float alpha;uniform float time;void main(){vec3 N=normalize(normal);vec3 V=normalize(eye-world);float rim=pow(1.-abs(dot(N,V)),2.2);float light=.16+max(dot(N,normalize(vec3(-.45,.6,.8))),0.)*.62;vec3 col=rgb*light+vec3(.07,.48,.64)*rim*.55;float a=alpha;if(emission>.5&&emission<1.5){col=rgb*1.3;}if(emission>1.5&&emission<2.5){float scan=.78+.22*sin(world.y*35.+time*.65);col=rgb*(.06+rim*1.9)*scan;a*=.18+rim*.78;}if(emission>2.5){vec3 q=N*4.;float land=sin(q.x*2.3+sin(q.y*3.))+cos(q.z*3.+sin(q.x*4.))+sin(q.y*4.7+q.z*2.);float detail=.65+.35*sin(q.x*31.+q.z*27.)*cos(q.y*25.);float mask=smoothstep(.0,.9,land);vec3 surface=mix(rgb*.045,rgb*.30,mask*detail);float spec=pow(max(dot(reflect(normalize(vec3(.45,-.6,-.8)),N),V),0.),26.);col=surface*(light+.2)+rgb*rim*1.25+vec3(.15,.45,.6)*spec*.35;a=alpha;}gl_FragColor=vec4(col,a);}`);
   this.loc={};for(const k of ['p','n','c'])this.loc[k]=gl.getAttribLocation(this.program,k);for(const k of ['vp','m','alpha','emission','eye','time'])this.loc[k]=gl.getUniformLocation(this.program,k);
   const quad=`attribute vec2 q;varying vec2 uv;void main(){uv=q*.5+.5;gl_Position=vec4(q,0.,1.);}`;
   this.extract=this.compile(quad,`precision mediump float;varying vec2 uv;uniform sampler2D tex;void main(){vec3 c=texture2D(tex,uv).rgb;float b=max(c.r,max(c.g,c.b));gl_FragColor=vec4(c*smoothstep(.28,.8,b),1.);}`);
   this.blur=this.compile(quad,`precision mediump float;varying vec2 uv;uniform sampler2D tex;uniform vec2 axis;void main(){vec3 c=texture2D(tex,uv).rgb*.227027;c+=texture2D(tex,uv+axis*1.384615).rgb*.316216;c+=texture2D(tex,uv-axis*1.384615).rgb*.316216;c+=texture2D(tex,uv+axis*3.230769).rgb*.070270;c+=texture2D(tex,uv-axis*3.230769).rgb*.070270;gl_FragColor=vec4(c,1.);}`);
   this.composite=this.compile(quad,`precision mediump float;varying vec2 uv;uniform sampler2D tex;uniform sampler2D bloom;uniform float aspect;void main(){vec3 scene=texture2D(tex,uv).rgb;vec3 glow=texture2D(bloom,uv).rgb;vec2 p=(uv-vec2(.5,.62))*vec2(aspect,1.);float nebula=exp(-dot(p,p)*7.);vec3 bg=vec3(.007,.020,.030)+vec3(.007,.038,.056)*nebula;float vignette=1.-smoothstep(.25,1.,length((uv-.5)*vec2(1.,.85)))*.28;float grain=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453)/420.;gl_FragColor=vec4((bg+scene*.91+glow*1.05)*vignette+grain,1.);}`);
   this.quad=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.quad);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);gl.clearColor(0,0,0,0);
  }
  compile(v,f){const gl=this.gl,p=gl.createProgram();for(const [kind,src]of[[gl.VERTEX_SHADER,v],[gl.FRAGMENT_SHADER,f]]){const s=gl.createShader(kind);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);gl.deleteShader(s)}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
  targetBuffer(w,h,depth=false){const gl=this.gl,tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);for(const [key,value]of[[gl.TEXTURE_MIN_FILTER,gl.LINEAR],[gl.TEXTURE_MAG_FILTER,gl.LINEAR],[gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE],[gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE]])gl.texParameteri(gl.TEXTURE_2D,key,value);const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);let rb=null;if(depth){rb=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,rb);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,w,h);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,rb)}if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('3D 화면 버퍼 초기화 실패');return {tex,fb,rb,w,h}}
  resize(w,h){const gl=this.gl;for(const b of this.buffers){gl.deleteTexture(b.tex);gl.deleteFramebuffer(b.fb);if(b.rb)gl.deleteRenderbuffer(b.rb)}this.buffers=[this.targetBuffer(w,h,true),this.targetBuffer(Math.max(1,w>>2),Math.max(1,h>>2)),this.targetBuffer(Math.max(1,w>>2),Math.max(1,h>>2))]}
  mesh(b){const gl=this.gl,buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(b.data),gl.STATIC_DRAW);const mesh={buffer,count:b.data.length/9};this.resources.push(mesh);return mesh}
  delete(m){if(m){this.gl.deleteBuffer(m.buffer);this.resources=this.resources.filter(x=>x!==m)}}
  begin(time=0){const gl=this.gl,r=this.canvas.getBoundingClientRect(),dpr=Math.min(Math.max(devicePixelRatio||1,1.25),1.5);this.width=r.width;this.height=r.height;const w=Math.max(1,Math.round(r.width*dpr)),hpx=Math.max(1,Math.round(r.height*dpr));if(this.canvas.width!==w||this.canvas.height!==hpx||!this.buffers.length){this.canvas.width=w;this.canvas.height=hpx;this.resize(w,hpx)}gl.bindFramebuffer(gl.FRAMEBUFFER,this.buffers[0].fb);gl.viewport(0,0,w,hpx);gl.depthMask(true);gl.enable(gl.DEPTH_TEST);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);for(const k of Object.keys(this.camera))this.camera[k]+=(this.target[k]-this.camera[k])*.065;for(const k of ['x','y'])this.parallax[k]+=(this.aim[k]-this.parallax[k])*.045;const a=this.camera.angle+this.parallax.x*.022,eye=[this.camera.x+Math.sin(a)*72,this.camera.y+29+this.parallax.y,this.camera.z+Math.cos(a)*72],at=[this.camera.x,this.camera.y,this.camera.z],aspect=r.width/Math.max(r.height,1);let h=23/this.camera.zoom;if(r.width<=750)h=44*.92/this.camera.zoom;else if(aspect<1.5)h*=1.5/aspect;this.vp=G.mul(ortho(h*aspect,h),look(eye,at));gl.useProgram(this.program);gl.uniformMatrix4fv(this.loc.vp,false,this.vp);gl.uniform3fv(this.loc.eye,eye);gl.uniform1f(this.loc.time,time)}
  draw(mesh,m=G.model(),glow=false,alpha=1){if(!mesh)return;const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,mesh.buffer);for(const [key,off] of [['p',0],['n',12],['c',24]]){gl.enableVertexAttribArray(this.loc[key]);gl.vertexAttribPointer(this.loc[key],3,gl.FLOAT,false,36,off)}gl.uniformMatrix4fv(this.loc.m,false,m);gl.uniform1f(this.loc.alpha,alpha);gl.uniform1f(this.loc.emission,typeof glow==='number'?glow:glow?1:0);if((glow&&glow!==3)||alpha<1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,glow?gl.ONE:gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false)}else{gl.disable(gl.BLEND);gl.depthMask(true)}gl.drawArrays(gl.TRIANGLES,0,mesh.count);gl.depthMask(true)}
  pass(program,from,to,axis){const gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,to?.fb||null);gl.viewport(0,0,to?.w||this.canvas.width,to?.h||this.canvas.height);gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,this.quad);const q=gl.getAttribLocation(program,'q');gl.enableVertexAttribArray(q);gl.vertexAttribPointer(q,2,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,from.tex);gl.uniform1i(gl.getUniformLocation(program,'tex'),0);if(axis)gl.uniform2fv(gl.getUniformLocation(program,'axis'),axis);if(program===this.composite){gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.buffers[1].tex);gl.uniform1i(gl.getUniformLocation(program,'bloom'),1);gl.uniform1f(gl.getUniformLocation(program,'aspect'),this.width/this.height)}gl.drawArrays(gl.TRIANGLES,0,6)}
  finish(){const gl=this.gl;gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);this.pass(this.extract,this.buffers[0],this.buffers[1]);this.pass(this.blur,this.buffers[1],this.buffers[2],[1/this.buffers[1].w,0]);this.pass(this.blur,this.buffers[2],this.buffers[1],[0,1/this.buffers[1].h]);this.pass(this.composite,this.buffers[0],null)}
  project(x,y,z){const p=[x,y,z,1],v=[0,0,0,0];for(let row=0;row<4;row++)for(let k=0;k<4;k++)v[row]+=this.vp[k*4+row]*p[k];return {x:(v[0]/v[3]+1)*this.width/2,y:(1-v[1]/v[3])*this.height/2}}
 }
 function segment(b,a,z,r,col){const d=norm(sub(z,a)),u=norm(cross(d,Math.abs(d[1])>.9?[1,0,0]:[0,1,0])),v=cross(d,u),p=(o,i)=>o.map((n,k)=>n+r*(u[k]*Math.cos(i*Math.PI/3)+v[k]*Math.sin(i*Math.PI/3)));for(let i=0;i<6;i++)b.quad(p(a,i),p(z,i),p(z,i+1),p(a,i+1),col)}
 function ring(b,r,col,plane='xz',start=0,end=Math.PI*2,thick=.035){const N=100;let prev;for(let i=0;i<=N;i++){const a=start+(end-start)*i/N,p=plane==='xy'?[Math.cos(a)*r,Math.sin(a)*r,0]:plane==='yz'?[0,Math.cos(a)*r,Math.sin(a)*r]:[Math.cos(a)*r,0,Math.sin(a)*r];if(prev)segment(b,prev,p,thick,col);prev=p}}
 function curve(a,b,lift=0){const out=[];for(let i=0;i<=36;i++){const t=i/36;out.push(a.map((v,k)=>v+(b[k]-v)*t+(k===1?Math.sin(t*Math.PI)*lift:0)))}return out}
 function tube(points,col,r=.035,dashed=false){const b=new G.MeshBuilder();for(let i=1;i<points.length;i++)if(!dashed||i%4<2)segment(b,points[i-1],points[i],r,col);return b}
 function point(points,t){const n=Math.min(.9999,Math.max(0,t))*(points.length-1),i=Math.floor(n),u=n-i;return points[i].map((v,k)=>v+(points[i+1][k]-v)*u)}
 window.Cosmos3D={...G,Engine,segment,ring,curve,tube,point};
})();
