(()=>{'use strict';
const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),V=window.VillageModel,M=window.EcosystemModel,G=window.Cosmos3D,root=$('#ecosystem'),canvas=$('#ecoCanvas');
const colors={working:'#52d6ff',connected:'#258fff',recent:'#50c9f5',ok:'#4bcaeb',recorded:'#62bfcf',done:'#447d9e',blocked:'#ff5069',error:'#ff5069',quiet:'#e9b761',waiting:'#a79572',paused:'#d5ab64',unknown:'#3c6179',empty:'#264e69'};
let groups=[];
const brain=[0,13.5,-7],dispatcher=[0,1.6,-1],planetSites=[[-25,-3.2,8],[-15,-3.2,3],[-5,-3.2,0],[5,-3.2,0],[15,-3.2,3],[25,-3.2,8]];
let engine=null,rawSlack=null,pipeline=null,operations=null,view=null,sources=[],nodes=[],links=[],flows=[],selection=null,lastSlack=0,pipeFailed=false,slackFailed=false,signature='',lastDraw=0,lastLabels=0,hover=null,drag=null,problemOnly=false,motion=!matchMedia('(prefers-reduced-motion:reduce)').matches,demo=false,demoStart=0,demoPhase=-1,polling=false,sourceCounts=null,history=[],signalAt=0,lastClock=0;
const opTracker=M.freshTracker(),memoryTracker=M.freshTracker(),art={},visualCache=new Map();
const desktopPlanets=planetSites.map(p=>[...p]);
let smallLayout=false;const floatSizes=new Map();let animationTime=0,previousFrame=0;
function layout(){
 const width=root.clientWidth||window.innerWidth||1600;smallLayout=width<=750;
 const sx=Math.min(1,width/538),half=Math.ceil(groups.length/2);
 groups.forEach((g,i)=>{const right=i>=half,row=right?i-half:i,rows=right?groups.length-half:half;g.pos=smallLayout?[(right?22:-22)*sx,39-row*(42/Math.max(7,rows-1)),0]:[right?24:-24,21-Math.max(1.9,Math.min(5,(1050-(root.clientHeight||1000))/43))-row*(19.6/Math.max(7,rows-1)),-4];g.side=right?'right':'left'});
 brain.splice(0,3,...(smallLayout?[0,25,0]:[0,13.5,-7]));dispatcher.splice(0,3,...(smallLayout?[0,3.5,0]:[0,1.6,-1]));
 planetSites.forEach((p,i)=>p.splice(0,3,...(smallLayout?[(i%2?10:-10)*sx,-5-Math.floor(i/2)*11.5,3]:desktopPlanets[i].map((v,k)=>k===1?v+Math.max(0,(950-(root.clientHeight||1000))/((root.clientHeight||1000)<=800?75:55)):v))));
}
layout();

const visible=()=>!root.hidden&&!document.hidden,clock=t=>t?new Date(t*1000).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'없음',date=t=>t?new Date(t*1000).toLocaleString('ko-KR'):'기록 없음',count=n=>n==null?'—':Number(n).toLocaleString('ko-KR'),mesh=b=>engine.mesh(b),color=s=>colors[s]||colors.unknown;
const rotateZ=a=>new Float32Array([Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1,0,0,0,0,1]);
const rotateX=a=>new Float32Array([1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1]);
function isOffline(){return !demo&&(!rawSlack||slackFailed||Date.now()-lastSlack>26000)}
function outsideFocus(n){const id=selection?.type==='planet'?selection.id:selection?.type==='department'?nodes.find(x=>x.id===selection.id)?.project:null;return !!id&&(n.type==='planet'?n.id!==id:n.type==='department'?n.project!==id:true)}
function sourceStatus(s){return s==='connected'?'연결 유지':s==='recent'?'누적 보관':s==='empty'||s==='waiting'?'미적재':s==='quiet'?'최근 수집 확인':s==='recorded'?'저장 확인':s==='unknown'?'경로 확인 중':M.names[s]}
function sourceGroups(data){
 const rows=data?.sources||[];groups=rows.map(r=>({id:r.id,name:r.name,mark:r.mark||'+',ids:[r.id]}));layout();
 return groups.map((g,i)=>{const r=rows[i],available=!!data&&!pipeFailed&&data.brain?.readable!==false;return {...g,...r,rows:[r],state:available?(M.sourceConnected(r,data)?'connected':r.connection==='paused'?'paused':r.state):'unknown',count:r.count,displayCount:r.displayCount,lastKnown:pipeFailed}});
}
function currentSlack(){if(demo)return example();if(!rawSlack)return null;const use=operations&&operations.checked>=rawSlack.checked,newTasks=new Map((use?operations.tasks:[]).map(t=>[t.id,t]));return {...rawSlack,conversations:rawSlack.conversations.map(r=>({...r,tasks:r.tasks.map(t=>{const fresh=newTasks.get(t.id);return fresh?{...t,...fresh,roleName:t.roleName,shortTitle:t.shortTitle,reasonBrief:fresh.status===t.status&&fresh.reason===t.reason?t.reasonBrief:M.reason(fresh)}:t})}))}}
function signal(message,state='working'){signalAt=performance.now();$('#ecoSignal').textContent=message;$('#ecoSignal').style.color=color(state);history.unshift({at:Date.now()/1000,text:message,state});history=history.slice(0,20);$('#ecoEvents').innerHTML=`<time>${clock(history[0].at)}</time>${E(message)}`}
function translatedRing(b,r,y,col,plane='xz',start=0,end=Math.PI*2,thick=.025){const temp=new G.MeshBuilder();G.ring(temp,r,col,plane,start,end,thick);for(let i=0;i<temp.data.length;i+=9)temp.data[i+1]+=y;b.data.push(...temp.data)}
function materials(){
 const stars=new G.MeshBuilder();for(let i=0;i<360;i++){const x=Math.sin(i*79.7)*58,y=Math.sin(i*13.41)*32+10,z=-26-Math.abs(Math.cos(i*31.3))*25;stars.ellipsoid(x,y,z,.021+(i%4)*.012,.021+(i%4)*.012,.025,i%4?'#20556d':'#7dcadd',4,3)}art.stars=mesh(stars);
 const grid=new G.MeshBuilder();for(let x=-46;x<=46;x+=2)G.segment(grid,[x,-12,-28],[x,-12,35],.008,x%10?'#123242':'#1b4c5b');for(let z=-28;z<=35;z+=2)G.segment(grid,[-46,-12,z],[46,-12,z],.008,z%10?'#123242':'#1b4c5b');for(const r of [17,25,34,42])translatedRing(grid,r,-12,'#256077','xz',0,Math.PI*2,.012);art.grid=mesh(grid);
 const brainBody=new G.MeshBuilder();brainBody.ellipsoid(-1.38,0,0,2.6,3.15,2.25,'#339bc9',40,26);brainBody.ellipsoid(1.38,0,0,2.6,3.15,2.25,'#38aed0',40,26);art.brainBody=mesh(brainBody);
 const neurons=new G.MeshBuilder();for(let side of [-1,1]){for(let row=0;row<20;row++){const points=[];for(let j=0;j<=68;j++){const phi=j/68*Math.PI*2,v=-.91+row/19*1.82+Math.sin(phi*5+row*1.7)*.055,r=Math.sqrt(Math.max(.015,1-v*v)),fold=1+Math.sin(phi*8+row*2.1)*.055;points.push([side*(1.18+Math.cos(phi)*2.55*r*fold),v*3.1,Math.sin(phi)*2.25*r*fold])}for(let j=1;j<points.length;j++)G.segment(neurons,points[j-1],points[j],.014,row%3?'#399eb8':'#7cdbe5')}for(let i=0;i<310;i++){const a=i*2.39996,v=-.96+i/309*1.92,r=Math.sqrt(1-v*v);neurons.ellipsoid(side*(1.18+Math.cos(a)*2.6*r),v*3.15,Math.sin(a)*2.25*r,.035,.035,.035,i%7?'#59c9e1':'#d6ffff',4,3)}}art.neurons=mesh(neurons);
 const annulus=(b,r,w,col,start=0,end=Math.PI*2)=>{for(let i=0;i<96;i++){const a=start+(end-start)*i/96,z=start+(end-start)*(i+1)/96,p=(r,a)=>[Math.cos(a)*r,Math.sin(a)*r,0];b.quad(p(r,a),p(r+w,a),p(r+w,z),p(r,z),col)}};
 const arc=new G.MeshBuilder();for(const [r,start,end] of [[5.25,.15,2.72],[5.25,3.08,5.9],[6.25,.8,3.8],[7.35,4.2,6.45],[8.7,.3,1.3]])annulus(arc,r,.07,'#7adeea',start,end);for(let i=0;i<80;i++){const a=i/80*Math.PI*2;G.segment(arc,[Math.cos(a)*5.63,Math.sin(a)*5.63,0],[Math.cos(a)*(i%5?5.83:6.03),Math.sin(a)*(i%5?5.83:6.03),0],.02,i%5?'#339caf':'#b8f6ee')}art.arc=mesh(arc);
 const cage=new G.MeshBuilder();for(const [r,col]of[[6.7,'#258ba9'],[8.3,'#2d6e85'],[9.4,'#1f5268']])G.ring(cage,r,col,'xy',0,Math.PI*2,.015);for(let i=0;i<180;i++){const a=i/180*Math.PI*2;G.segment(cage,[Math.cos(a)*9.52,Math.sin(a)*9.52,0],[Math.cos(a)*(i%15?9.61:9.9),Math.sin(a)*(i%15?9.61:9.9),0],.013,i%15?'#286577':'#e1b574')}for(let i=0;i<8;i++){const a=i*Math.PI/4;G.segment(cage,[Math.cos(a)*8.32,Math.sin(a)*8.32,0],[Math.cos(a)*8.75,Math.sin(a)*8.75,0],.055,'#71c8d1')}art.cage=mesh(cage);
 const orbit=new G.MeshBuilder();G.ring(orbit,7.5,'#53d3ea','xz',.1,5.8,.028);G.ring(orbit,7.8,'#226477','xz',.8,4.7,.016);art.orbit=mesh(orbit);
 const gold=new G.MeshBuilder();for(let i=0;i<12;i++){const a=i/12*Math.PI*2;annulus(gold,7.03,.09,i%3?'#b88d53':'#e9c985',a,a+.13)}art.gold=mesh(gold);
 const dust=new G.MeshBuilder();for(let i=0;i<400;i++){const a=i*2.39996,y=Math.sin(i*2.18)*6.9,r=Math.sqrt(Math.max(0,53-y*y));dust.ellipsoid(Math.cos(a)*r,y,Math.sin(a)*r,.028,.028,.028,i%8?'#297e9b':'#95e7ef',4,3)}art.dust=mesh(dust);
 const core=new G.MeshBuilder();core.ellipsoid(0,0,0,.25,.25,.25,'#ecffff',12,9);art.photon=mesh(core);const halo=new G.MeshBuilder();halo.ellipsoid(0,0,0,.55,.55,.55,'#3ba4c2',16,10);art.photonHalo=mesh(halo);
 const scout=new G.MeshBuilder();const p=[[0,.78,0],[-.42,0,0],[0,0,.42],[.42,0,0],[0,0,-.42],[0,-.6,0]];for(let i=1;i<5;i++){const j=i===4?1:i+1;scout.tri(p[0],p[i],p[j],'#d9fff4');scout.tri(p[5],p[j],p[i],'#56bfd6')}G.ring(scout,.75,'#8beeff','xz',0,Math.PI*2,.021);art.agent=mesh(scout);
 const dispatch=new G.MeshBuilder();for(const [r,c] of [[.8,'#c8f9f6'],[1.3,'#4bafbe'],[2.2,'#2e6a80']])G.ring(dispatch,r,c,'xz',0,Math.PI*2,.028);for(let i=0;i<6;i++){let a=i*Math.PI/3;G.segment(dispatch,[Math.cos(a)*1.6,0,Math.sin(a)*1.6],[Math.cos(a)*1.8,0,Math.sin(a)*1.8],.04,'#ebc58a')}art.dispatch=mesh(dispatch);
}
function planetArt(key,tint){if(visualCache.has('planet:'+key))return visualCache.get('planet:'+key);const body=new G.MeshBuilder();body.ellipsoid(0,0,0,2.35,2.35,2.35,tint,40,28);const net=new G.MeshBuilder();
 for(let latitude=-4;latitude<=4;latitude++){const y=latitude*.46,r=Math.sqrt(2.37**2-y*y);translatedRing(net,r,y,tint,'xz',0,Math.PI*2,.012)}
 for(let j=0;j<6;j++){const a=j*Math.PI/6,points=[];for(let i=0;i<=72;i++){const t=i/72*Math.PI*2;points.push([Math.cos(t)*Math.cos(a)*2.38,Math.sin(t)*2.38,Math.cos(t)*Math.sin(a)*2.38])}for(let i=1;i<points.length;i++)G.segment(net,points[i-1],points[i],.012,tint)}
 const dots=new G.MeshBuilder();let seed=[...key].reduce((s,c)=>s+c.charCodeAt(0),1);for(let i=0;i<160;i++){const a=i*2.39996,v=-.96+i/159*1.92,r=Math.sqrt(1-v*v);if(Math.sin(a*3+seed)+Math.cos(v*11+seed)>.05){const x=Math.cos(a)*2.4*r,z=Math.sin(a)*2.4*r;dots.ellipsoid(x,v*2.4,z,.032,.032,.032,'#b0e7f1',4,3)}}
 const base=new G.MeshBuilder();for(const r of [2.9,3.25,3.8])translatedRing(base,r,-2.7,tint,'xz',0,Math.PI*2,r===3.25?.04:.015);for(let i=0;i<72;i++){let a=i/72*Math.PI*2;G.segment(base,[Math.cos(a)*3.84,-2.7,Math.sin(a)*3.84],[Math.cos(a)*(i%6?3.92:4.12),-2.7,Math.sin(a)*(i%6?3.92:4.12)],.017,i%6?tint:'#d4eff5')}
 const orbit=new G.MeshBuilder();G.ring(orbit,3.6,tint,'xz',.3,Math.PI*1.85,.025);const result={body:mesh(body),net:mesh(net),dots:mesh(dots),base:mesh(base),orbit:mesh(orbit)};visualCache.set('planet:'+key,result);return result}
function statusRing(state){const key='status:'+state;if(!visualCache.has(key)){const b=new G.MeshBuilder();translatedRing(b,3.55,-2.6,color(state),'xz',.12,Math.PI*1.9,.035);visualCache.set(key,mesh(b))}return visualCache.get(key)}
function sphere(state){const key='dot:'+state;if(!visualCache.has(key)){const b=new G.MeshBuilder();b.ellipsoid(0,0,0,.26,.26,.26,color(state),10,7);visualCache.set(key,mesh(b))}return visualCache.get(key)}
function rebuild(){layout();const raw=currentSlack();view=M.build(raw,demo?demoPipeline():pipeline,Date.now()/1000,isOffline());sources=sourceGroups(demo?demoPipeline():pipeline);if(demo)sources=sources.map(s=>({...s,state:'connected'}));
 const projects=view.projects.length?view.projects:V.places.map((style,i)=>({id:'pending:'+style.key,name:style.name,style,state:'unknown',tasks:[],requests:[],departments:[],completed:0,files:0,pending:true}));
 const next=[];sources.forEach(s=>next.push({key:'source:'+s.id,type:'source',id:s.id,name:s.name,pos:s.pos,state:s.state,data:s}));next.push({key:'brain',id:'brain',type:'brain',name:'MIMIR',pos:brain,state:pipeFailed||!pipeline&&!demo?'unknown':(pipeline?.brain.readable===false||pipeline?.jobs?.some(j=>j.state==='error'))&&!demo?'error':'recent'},{key:'dispatch',id:'dispatch',type:'dispatch',name:'업무 조율',pos:dispatcher,state:'working'});
 projects.forEach((p,i)=>{const pos=planetSites[V.places.findIndex(s=>s.key===p.style?.key)]||planetSites[i];next.push({key:'planet:'+p.id,type:'planet',id:p.id,name:p.name,pos,state:p.state,data:p});p.departments.forEach((d,j)=>{const a=j/Math.max(1,p.departments.length)*Math.PI*2-.4;next.push({key:'department:'+d.id,type:'department',id:d.id,project:p.id,name:d.name,pos:[pos[0]+Math.cos(a)*4.4,pos[1]+.65,pos[2]+Math.sin(a)*4.4],state:d.state,data:d})})});nodes=next;
 const key=JSON.stringify([nodes.map(n=>[n.key,n.state,n.pos,n.data?.completed,n.data?.tasks?.length]),view.reads.map(r=>[r.id,r.state])]);if(engine&&key!==signature){signature=key;links.forEach(l=>{engine.delete(l.mesh);engine.delete(l.halo)});links=[];const wire=(key,from,to,state,type,id,lift=0)=>{const points=G.curve(from,to,lift),stream=type==='source'&&state==='connected',dashed=['unknown','empty','waiting','quiet','paused'].includes(state),phase=[...key].reduce((a,c)=>a+c.charCodeAt(0),0)%37/37;links.push({key,points,state,type,id,stream,phase,mesh:mesh(G.tube(points,color(state),stream?.065:.018,dashed)),halo:mesh(G.tube(points,color(state),stream?.19:.05,dashed))})};
  for(const s of sources)wire('in:'+s.id,s.pos,brain,s.state,'source',s.id,1.3);wire('brain-dispatch',brain,dispatcher,nodes.find(n=>n.key==='brain').state,'brain','brain');
  for(const p of nodes.filter(n=>n.type==='planet')){wire('project:'+p.id,dispatcher,p.pos,p.state,'planet',p.id,1.8);for(const d of nodes.filter(n=>n.project===p.id))wire('dept:'+d.id,p.pos,d.pos,d.state,'department',d.id,.5)}
  for(const r of view.reads){const task=r.task,d=nodes.find(n=>n.type==='department'&&n.project===r.projectId&&n.data.agents.includes(task.assignee)),p=d||nodes.find(n=>n.id===r.projectId);if(p)wire('memory:'+r.id,p.pos,brain,r.state==='error'?'error':'recent','department',d?.id||'',2)}
 }
 const labelKey=nodes.map(n=>n.key).join('|');if($('#ecoLabels').dataset.keys!==labelKey){$('#ecoLabels').dataset.keys=labelKey;$('#ecoLabels').innerHTML=nodes.map(n=>`<button class="eco-label ${n.type}" data-eco-node="${E(n.key)}" aria-label="${E(n.name)} ${n.type==='department'?'부서':n.type==='planet'?'프로젝트':n.type==='source'?'데이터 연결':'상세'} 열기"></button>`).join('')}
 for(const n of nodes){const el=label(n.key);if(!el)continue;el.disabled=n.type==='planet'&&!!n.data.pending;const dim=outsideFocus(n)||problemOnly&&!['blocked','error','quiet'].includes(n.state);el.className='eco-label '+n.type+' '+n.state+(dim?' dim':'')+(n.data?.side?' '+n.data.side:'');el.hidden=n.type==='department'&&!(selection?.type==='planet'&&selection.id===n.project||selection?.type==='department'&&selection.id===n.id);let sub='';if(n.type==='planet'){const p=n.data;sub=p.pending?'기록 연결 중':p.tasks.length?`${p.completed}/${p.tasks.length} 업무 완료 · ${M.names[p.state]}`:p.requests.length?'진행 연결 확인':'아직 맡긴 일 없음';el.innerHTML=`<em>PROJECT / ${String(V.places.findIndex(a=>a.key===p.style.key)+1).padStart(2,'0')}</em><strong><i class="eco-state-dot"></i>${E(n.name)}</strong><small>${E(sub)}</small>${p.tasks.length?`<span class="eco-progress"><i style="width:${p.completed/p.tasks.length*100}%"></i></span>`:''}`}
 else if(n.type==='brain'){const p=demo?demoPipeline():pipeline;el.innerHTML=`<em>COMPANY INTELLIGENCE</em><strong>MIMIR</strong><small>${demo?'가상 기억 · 체험':`${count(p?.brain.recordedSources)}개 원천 · 누적 ${count(p?.brain.total)}건`}</small>`}
 else if(n.type==='source')el.innerHTML=`<span class="eco-source-icon" aria-hidden="true">${E(n.data.mark)}</span><strong><i class="eco-state-dot"></i>${E(n.data.derived?'GPT 대화':n.name)}</strong><small>${n.data.derived?'헤르메스 경유':sourceStatus(n.state)}</small><b class="eco-source-count">${demo?'예시':count(M.cumulativeCount(n.data))}<span>누적 건</span></b>`;
 else if(n.type==='department')el.innerHTML=`<strong>${E(n.name)}</strong><small>${n.data.tasks.length?M.names[n.state]+' · '+n.data.tasks.length+'개':'설치된 담당 '+n.data.agents.length+'명'}</small>`;
 else el.innerHTML='<strong>DISPATCH</strong><small>헤르메스 · 업무 분담</small>';
 }
 $('.eco-left-readout>span').textContent=demo?'WORKSPACE / 가상 체험':'WORKSPACE / LIVE';$('#ecoStats').innerHTML=[['working',isOffline()?'—':view.working,'작업 중'],['blocked',isOffline()?'—':view.blocked,'막힌 업무'],['done',view.completed,'업무 완료']].map(([s,n,l])=>`<div class="eco-stat ${s}"><b>${n}</b><span>${l}</span></div>`).join('');$('#ecoConnection').textContent=demo?'EXPERIENCE / 가상 업무':isOffline()?'실행 기록 연결 확인':pipeFailed?'데이터 연결 확인':'기록 갱신 '+clock(rawSlack?.checked);$('#ecoConnection').classList.toggle('stale',!demo&&(isOffline()||pipeFailed));$('#ecoStale').hidden=demo||!((rawSlack&&isOffline())||pipeFailed);$('#ecoStale').textContent='새 기록을 읽지 못한 연결은 미확인으로 표시. 실제 업무·데이터 이동은 잠시 멈춤.';$('#ecoSourceCount').textContent=demo?'가상 데이터':`전체 기간 누적 · ${count(pipeline?.brain.recordedSources)}개 원천`;renderDetail();
}
function label(key){return [...$('#ecoLabels').children].find(e=>e.dataset.ecoNode===key)}
function request(r){const tasks=r.tasks||[],s=M.aggregate(tasks);return `<button class="eco-request" data-eco-request="${E(r.id)}"><em>${E(r.user||'요청자 미확인')} · ${M.names[s]}</em><strong>${E(r.summary||r.title||'맡긴 일')}</strong><small>업무 ${tasks.filter(t=>t.status==='done').length}/${tasks.length} 완료 · 결과 파일 ${r.attachments?.length||0}개</small></button>`}
function renderDetail(){const box=$('#ecoInspector'),body=$('#ecoDetail');box.hidden=!selection;box.classList.toggle('catalog-open',selection?.type==='sources');root.classList.toggle('eco-detail-open',!!selection);if(!selection||!view)return;let html='',n=nodes.find(n=>n.type===selection.type&&n.id===selection.id);
 if(selection.type==='planet'&&n){const p=n.data;html=`<span class="eco-detail-eyebrow">PROJECT / ${E(M.names[p.state])}</span><h2>${E(p.name)}</h2><div class="eco-detail-stats"><span><b>${p.requests.length}</b><small>맡긴 요청</small></span><span><b>${p.completed}/${p.tasks.length}</b><small>업무 완료</small></span><span><b>${p.files}</b><small>결과 파일</small></span></div><h3>참여 부서 · 눌러서 맡은 일 보기</h3><div class="eco-departments">${p.departments.map(d=>`<button class="eco-dept ${d.state}" data-eco-node="department:${E(d.id)}"><strong>◈ ${E(d.name)}</strong><small>${d.agents.length}명 · ${d.tasks.length?M.names[d.state]+' / '+d.tasks.length+'개':'배정 기록 없음'}</small></button>`).join('')}</div><h3>팀이 맡긴 일</h3>${p.requests.map(request).join('')||'<p class="eco-empty">아직 이 프로젝트에 연결된 요청 기록이 없음.</p>'}<p class="eco-detail-note">완료 비율은 등록된 세부 업무 개수 기준. 작업 시간이나 품질을 추정한 수치는 아님.</p>`}
 else if(selection.type==='department'&&n){const d=n.data,p=view.projects.find(p=>p.id===n.project),agents=new Map((currentSlack()?.agents||[]).map(a=>[a.id,a]));html=`<span class="eco-detail-eyebrow">${E(p?.name||'PROJECT')} / DEPARTMENT</span><h2>${E(d.name)}</h2><p>${M.names[d.state]} · 맡은 업무 ${d.tasks.length}개</p>${d.agents.map(id=>`<div class="eco-person"><i>◇</i><span>${E(agents.get(id)?.role||d.tasks.find(t=>t.assignee===id)?.roleName||id)}</span></div>`).join('')}<h3>지금 이 부서에 맡겨진 일</h3>${d.tasks.map(t=>`<div class="eco-task ${M.state(t)}"><b>${E(t.shortTitle||t.title)}</b><small>${M.names[M.state(t)]}${M.reason(t)?' · '+E(M.reason(t)):''}</small></div>`).join('')||'<p class="eco-empty">연결된 담당은 있지만 실제 배정된 업무 기록은 아직 없음.</p>'}<h3>원래 요청과 결과</h3>${view.requests.filter(r=>r.tasks.some(t=>d.tasks.some(x=>x.id===t.id))).map(request).join('')}`}
 else if(selection.type==='source'&&n){const s=n.data;html=`<span class="eco-detail-eyebrow">${E(s.category||'DATA SOURCE')} / MIMIR</span><h2>${E(s.name)}</h2><p>${E(s.what||'저장된 자료')}.</p><div class="eco-detail-stats"><span><b>${count(M.cumulativeCount(s))}</b><small>${s.derived?'누적 · 기존 기록에 포함':'전체 누적 기록'}</small></span>${s.usable!=null?`<span><b>${count(s.usable)}</b><small>내용 저장 · 누적</small></span>`:''}</div><div class="eco-route">${E(s.route||'자료 → 미미르')}</div>${s.cadence?`<p class="eco-cadence">◷ ${E(s.cadence)}</p>`:''}<h3>현재까지 쌓인 내용</h3><div class="eco-breakdown">${(s.parts||[]).map(r=>`<div class="${r.issue?'issue':''}"><span>${E(r.name)}</span><b>${count(r.count)}</b></div>`).join('')||'<p>세부 항목은 추가 확인 중.</p>'}</div><div class="eco-source-row ${s.state}"><strong>${E(sourceStatus(s.state))}</strong>${s.lastAdded?`<small>마지막 적재 ${date(s.lastAdded)}</small>`:''}<small>${E(s.note)}</small></div>${s.connectionNote?`<p class="eco-detail-note">${E(s.connectionNote)}</p>`:''}${s.needsReview?'<p class="eco-detail-note">보류·실패·글자 없음은 별도 기록. 이 수를 내용 저장이나 학습 완료로 계산하지 않음.</p>':''}<button class="eco-primary" data-eco-catalog>모든 데이터 연결 보기 ↗</button>`}
 else if(selection.type==='sources'){const p=demo?demoPipeline():pipeline;html=`<span class="eco-detail-eyebrow">MIMIR / DATA ATLAS</span><h2>미미르에 들어오는 것들</h2><p>${count(p?.brain.recordedSources)}개 원천에서 수집 확인 · 새로운 원천은 자동 추가</p><div class="eco-detail-stats"><span><b>${count(p?.brain.total)}</b><small>전체 누적 기록</small></span><span><b>${count(p?.brain.facts)}</b><small>정리된 지식</small></span></div>${[...new Set(sources.map(s=>s.category||'자료'))].map(category=>`<h3>${E(category)}</h3><div class="eco-source-catalog">${sources.filter(s=>(s.category||'자료')===category).map(s=>`<button class="eco-catalog-item ${s.state}" data-eco-node="source:${E(s.id)}"><span class="eco-catalog-mark">${E(s.mark)}</span><span><strong>${E(s.name)}</strong><small>${E(s.what||s.note)}</small><em>${E(s.derived?'다른 원천에 포함 · 중복 제외':sourceStatus(s.state))}</em></span><b>${count(M.cumulativeCount(s))}<small>누적 건</small></b></button>`).join('')}</div>`).join('')}<p class="eco-detail-note">모든 숫자는 기간 제한 없이 현재 저장된 전체 누적 기록 수. Drive·문서·사진과 GPT·헤르메스처럼 겹치는 경로는 전체 합계에서 중복 제외. 메일 보류·실패, 문서 읽기 실패 등도 전체 기록에는 포함. 각 원천을 누르면 내용 저장과 예외 항목을 구분해서 확인.</p>`}
 else if(selection.type==='brain'){const p=demo?demoPipeline():pipeline;html=`<span class="eco-detail-eyebrow">MIMIR / COMPANY MEMORY</span><h2>우리 회사의 기억</h2><div class="eco-detail-stats"><span><b>${count(p?.brain.total)}</b><small>전체 누적 기록</small></span><span><b>${count(p?.brain.facts)}</b><small>정리된 지식</small></span></div><button class="eco-primary" data-eco-catalog>모든 데이터 연결 보기 ↗</button><p class="eco-detail-note">수집한 자료에서 회사 지식을 뽑아 기억하고 검색에 활용. 이 숫자는 LLM 자체의 재학습 횟수가 아님.</p><h3>기억을 모으고 정리하는 장치</h3>${(p?.jobs||[]).map(j=>`<div class="eco-source-row ${j.state}"><strong>${E(j.name)} · ${M.names[j.state]}${j.cadence?' / '+E(j.cadence):''}</strong><small>최근 실행 ${date(j.at)}</small></div>`).join('')}<h3>최근 감지된 정보 조회</h3>${view.reads.slice(0,7).map(r=>`<div class="eco-source-row"><strong>${E(r.task.roleName||'담당')} · ${r.state==='returned'?'조회 명령 완료':r.state==='error'?'조회 명령 실패':'조회 요청'}</strong><small>${date(r.at)} · ${E(r.task.shortTitle||r.task.title)}</small></div>`).join('')||'<p class="eco-empty">최근 1시간에 이 여섯 프로젝트의 업무와 연결된 조회 기록이 감지되지 않음. 실제 조회가 없었다는 단정은 아님.</p>'}<p class="eco-detail-note">정보 조회 선은 회사 기억 조회 명령과 업무 번호가 함께 확인됐을 때만 표시. 도구 기록이 없거나 업무 번호가 연결되지 않은 조회는 행성에 임의로 연결하지 않음.</p>`}
 else if(selection.type==='request'){const r=view.requests.find(r=>r.id===selection.id);if(!r){selection=null;return renderDetail()}html=`<span class="eco-detail-eyebrow">TASK / ${E(r.user||'요청자 미확인')}</span><h2>${E(r.summary||r.title)}</h2>${r.tasks.map(t=>`<div class="eco-task ${M.state(t)}"><b>${E(t.roleName||'담당 확인')} · ${E(t.shortTitle||t.title)}</b><small>${M.names[M.state(t)]}${M.reason(t)?' · '+E(M.reason(t)):''}</small></div>`).join('')}<button class="eco-primary" data-eco-report="${E(r.id)}">보고와 결과 파일 열기 ↗</button>`}
 else if(selection.type==='problems'){html='<span class="eco-detail-eyebrow">ATTENTION / 확인할 곳</span><h2>흐름이 막힌 곳</h2>'+view.alerts.map(a=>`<button class="eco-alert ${a.level}" ${a.project?`data-eco-node="planet:${E(a.project)}"`:a.source?`data-eco-node="source:${E(groups.find(g=>g.ids.includes(a.source))?.id||'work')}"`:'data-eco-node="brain"'}><em>${a.level==='blocked'?'오류·막힘':'확인 필요'}</em><strong>${E(a.name)}</strong><small>${E(a.message)}</small></button>`).join('')+(view.alerts.length?'':'<p class="eco-empty">현재 확인된 막힘이나 수집 지연 경고 없음.</p>')}
 else if(selection.type==='results'){html=`<span class="eco-detail-eyebrow">OUTPUT / 여섯 프로젝트</span><h2>도착한 결과</h2><p>연결된 결과 파일 ${view.files}개 · 중간 결과 포함</p>${view.requests.filter(r=>(r.attachments||[]).length||r.tasks.some(t=>t.result)).map(request).join('')||'<p class="eco-empty">아직 연결된 결과 없음.</p>'}`}
 else if(selection.type==='evidence'){html='<span class="eco-detail-eyebrow">HOW TO READ</span><h2>이 공간을 읽는 법</h2><div class="eco-source-row recent"><strong>굵은 파란 선 + 흐르는 빛</strong><small>수집 연결이 유지되는 경로. 빛은 연결 상태를 표현하며 개별 파일의 실시간 전송이나 속도를 뜻하지 않음.</small></div><div class="eco-source-row error"><strong>빨간 선</strong><small>현재 작업에 기록된 막힘·실패. 해당 선이나 행성을 누르면 이유 확인.</small></div><div class="eco-source-row quiet"><strong>노란 선</strong><small>진행 신호가 오래됐거나 새 자료가 오래 없는 곳. 실제 중단 여부 확인 필요.</small></div><div class="eco-source-row"><strong>회색 점선</strong><small>기록 미확인 또는 아직 들어온 자료 없음.</small></div><p>파란 선 위의 반복되는 빛은 연결 유지 표시. 별도의 업무 배달부와 알림은 새 배정·완료·자료 적재·정보 조회 기록을 표현. 별의 회전과 빛은 배경 효과.</p><p>완료 수는 등록된 업무 개수 기준. 완료 표시만으로 Slack 보고 전달이나 결과 품질을 보장하지 않음.</p>'}
 else {html=`<span class="eco-detail-eyebrow">HERMES / WORKSPACE</span><h2>${selection.type==='dispatch'?'업무를 나누는 헤르메스':'여섯 프로젝트'}</h2><p>${view.requests.length}개 요청 · ${view.tasks.length}개 세부 업무</p>${view.projects.map(p=>`<button class="eco-request" data-eco-node="planet:${E(p.id)}"><strong>${E(p.name)}</strong><small>${p.requests.length}개 요청 · ${p.completed}/${p.tasks.length}개 업무 완료 · ${p.departments.length}개 부서</small></button>`).join('')}`}
 const scroll=body.scrollTop;if(body.innerHTML!==html){body.innerHTML=html;body.scrollTop=scroll}
}
function focus(type,id){if(type==='sources'&&engine)engine.target={angle:.04,zoom:.92,x:0,y:smallLayout?7:8,z:3};selection={type,id};$('#ecoDetail').scrollTop=0;const n=nodes.find(n=>n.type===type&&n.id===id);if(engine&&n){const pos=n.pos;engine.target={angle:.08,zoom:type==='planet'||type==='department'?1.9:type==='brain'?1.08:1.1,x:pos[0]+(engine.width>850?5:0),y:pos[1]+3,z:pos[2]+2}}rebuild()}
function home(){selection=null;problemOnly=false;$('#ecoProblems').setAttribute('aria-pressed','false');if(engine)engine.target={angle:.04,zoom:.92,x:0,y:smallLayout?7:8,z:3};rebuild()}
function flow(points,kind,message,state='working',duration=5200){if(!engine||!motion||!visible()||!demo&&isOffline())return;flows.push({points,kind,state,started:performance.now(),duration});if(flows.length>12)flows.shift();signal(message,state)}
function taskFlow(e){const t=view?.tasks.find(t=>t.id===e.task_id);if(!t)return;const p=nodes.find(n=>n.type==='planet'&&t.projectIds.includes(n.id)),d=nodes.find(n=>n.type==='department'&&n.project===p?.id&&n.data.agents.includes(t.assignee));if(!p)return;if(['assigned','claimed','spawned'].includes(e.kind)){const points=[...G.curve(dispatcher,p.pos,2),...G.curve(p.pos,d?.pos||p.pos,1).slice(1)];flow(points,'agent',`${p.name} · ${t.roleName||'담당'}에게 업무 전달`)}else if(e.kind==='completed')flow(G.curve(d?.pos||p.pos,dispatcher,2),'agent',`${p.name} · ${t.roleName||'담당'} 업무 완료`);else if(['blocked','crashed','timed_out','gave_up'].includes(e.kind))signal(`${p.name} · ${t.roleName||'담당'} 업무 확인 필요`,'blocked')}
function memoryFlow(r){const t=view?.tasks.find(t=>t.id===r.taskId);if(!t)return;const d=nodes.find(n=>n.type==='department'&&t.projectIds.includes(n.project)&&n.data.agents.includes(t.assignee)),p=d||nodes.find(n=>n.type==='planet'&&t.projectIds.includes(n.id));if(!p)return;flow(G.curve(r.state==='returned'?brain:p.pos,r.state==='returned'?p.pos:brain,2),'data',`${t.roleName||'담당'} · ${r.state==='returned'?'미미르 조회 명령 완료':r.state==='error'?'미미르 조회 실패':'미미르 정보 조회 요청'}`,r.state==='error'?'error':'working')}
function draw(now){requestAnimationFrame(draw);if(!engine||!visible()||now-lastDraw<32)return;const dt=Math.min(60,now-(previousFrame||now));previousFrame=now;lastDraw=now;if(motion)animationTime+=dt/1000;const t=animationTime;engine.begin(t);engine.draw(art.stars,G.model(0,0,0,1,motion?Math.sin(t*.025)*.006:0),true,.55);engine.draw(art.grid,G.model(),true,.13);
 for(const n of nodes.filter(n=>n.type==='planet')){const index=planetSites.indexOf(n.pos),a=planetArt(n.data.style?.key||n.id,['#4899bd','#48a5b8','#7788c7','#50aecc','#6aacc7','#b3a276'][index]||'#48aacc'),hot=hover?.key===n.key||selection?.type==='planet'&&selection.id===n.id,size=floatSizes.get(n.key)||1,next=size+((hot?1.18:1)-size)*.11;floatSizes.set(n.key,next);const dim=outsideFocus(n)?.15:problemOnly&&!['blocked','quiet'].includes(n.state)?.2:1,m=G.model(n.pos[0],n.pos[1]+(next-1)*4,n.pos[2],next,t*.075*(index%2?1:-1));engine.draw(a.body,m,3,dim);engine.draw(a.net,m,true,.16*dim);engine.draw(a.dots,m,true,.6*dim);engine.draw(a.base,G.model(...n.pos),true,(hot?.9:.44)*dim);engine.draw(a.orbit,G.mul(G.model(...n.pos,next),G.mul(rotateX(.4+index*.14),G.model(0,0,0,1,-t*.11))),true,.65*dim);if(['blocked','quiet','working'].includes(n.state))engine.draw(statusRing(n.state),G.model(...n.pos),true,.75);}
 const coreScale=smallLayout?.95:1,corePlace=G.model(...brain,coreScale),cortex=G.mul(corePlace,G.model(0,0,0,1,Math.sin(t*.085)*.32));const coreImage=$('#ecoCoreArt'),coreReady=coreImage?.complete&&coreImage.naturalWidth>0;if(!coreReady){engine.draw(art.brainBody,cortex,2,.55);engine.draw(art.neurons,cortex,true,.7)}engine.draw(art.dust,G.mul(corePlace,G.model(0,0,0,1,t*.024)),true,.22);engine.draw(art.cage,corePlace,true,.66);engine.draw(art.arc,G.mul(corePlace,rotateZ(t*.085)),true,.8);engine.draw(art.gold,G.mul(corePlace,rotateZ(-t*.045)),true,.75);engine.draw(art.orbit,G.mul(corePlace,G.mul(rotateX(.67+Math.sin(t*.08)*.15),G.model(0,0,0,1,t*.07))),true,.73);engine.draw(art.orbit,G.mul(corePlace,G.mul(rotateX(-.7),G.model(0,0,0,.84,-t*.1))),true,.38);engine.draw(art.dispatch,G.model(...dispatcher,1,t*.08),true,.8);
 for(const n of nodes.filter(n=>n.type==='source'||n.type==='department')){const dim=outsideFocus(n)||problemOnly&&!['blocked','error','quiet'].includes(n.state);engine.draw(sphere(n.state),G.model(...n.pos,n.type==='source'?.75:.85),true,dim?.16:.85);if(n.type==='department')engine.draw(art.agent,G.model(...n.pos,.48,t*.15),true,dim?.12:.5);if(n.state==='working'&&motion)engine.draw(art.photonHalo,G.model(...n.pos,.7+Math.sin(t*3)*.12),2,.65)}
 for(const l of links){
  const focusedNode=nodes.find(n=>n.type===l.type&&n.id===l.id),dim=(focusedNode&&outsideFocus(focusedNode))||problemOnly&&!['blocked','error','quiet'].includes(l.state),live=l.stream&&(demo||!pipeFailed&&M.sourceConnected(focusedNode?.data||{},pipeline)),alpha=dim?.06:live?.82:l.state==='blocked'||l.state==='error'?.8:l.key.startsWith('memory:')?.7:l.key.startsWith('in:')?.24:.32;
  engine.draw(l.halo,G.model(),true,alpha*(live?.32:.22));engine.draw(l.mesh,G.model(),true,alpha);
  // Repeating pulses represent a maintained connection, not synthetic arrivals.
  // They never create events or change cumulative counts.
  if(live&&motion&&!dim)for(let packet=0;packet<2;packet++){
   const progress=(t*.19+l.phase+packet*.5)%1,pos=G.point(l.points,progress);
   engine.draw(art.photon,G.model(...pos,.62),true,.93);
   for(let j=1;j<=6;j++){const tail=progress-j*.01;if(tail<0)continue;engine.draw(sphere('connected'),G.model(...G.point(l.points,tail),.54-j*.045),true,(1-j/7)*.65)}
  }
 }
 for(let i=flows.length-1;i>=0;i--){const f=flows[i],p=(now-f.started)/f.duration;if(p>=1){flows.splice(i,1);continue}const pos=G.point(f.points,p);engine.draw(f.kind==='agent'?art.agent:art.photon,G.model(...pos,f.kind==='agent'?1.35:1.1,t*2),true,1);for(let j=1;j<14;j++){const q=p-j*.012;if(q<0)continue;engine.draw(sphere(f.state),G.model(...G.point(f.points,q),.9-j*.047),true,(1-j/14)*.75)}}
 engine.finish?.();
 if(now-lastLabels>45){lastLabels=now;for(const n of nodes){const el=label(n.key);if(!el)continue;const y=n.pos[1]+(n.type==='planet'?-4.1:n.type==='brain'?smallLayout?-13.2:-10.6:n.type==='department'?1.1:1.05),p=engine.project(n.pos[0],y,n.pos[2]),below=n.type==='planet';el.style.transform=`translate(${Math.round(p.x)}px,${Math.round(p.y)}px) translate(-50%,${below?'0%':'-100%'})`;el.style.visibility=p.x<15||p.x>engine.width-15||p.y<(smallLayout?12:80)||p.y>engine.height-(smallLayout?6:97)?'hidden':'visible';el.classList.toggle('hovered',hover?.key===n.key);el.style.zIndex=n.type==='department'?'4':n.type==='planet'?'3':'2'}const p=engine.project(...brain);$('#ecoHalo').style.left=p.x+'px';$('#ecoHalo').style.top=p.y+'px';if(coreImage){const edge=engine.project(brain[0]+10.1,brain[1],brain[2]),size=Math.abs(edge.x-p.x)*2*(smallLayout?Math.min(1,(root.clientWidth||538)/480):1);coreImage.style.width=size+'px';coreImage.style.left=p.x+'px';coreImage.style.top=p.y+'px';coreImage.style.opacity=selection&&['planet','department'].includes(selection.type)?'.12':'1';coreImage.style.transform=`translate(-50%,-61%) perspective(700px) rotateY(${(engine.parallax?.x||0)*8+Math.sin(t*.17)*2}deg) rotateX(${(engine.parallax?.y||0)*-5}deg)`}}
 if(now-signalAt>6500)$('#ecoSignal').textContent='';if(demo&&motion){const phase=Math.min(6,Math.floor((now-demoStart)/4800));if(phase!==demoPhase){demoPhase=phase;rebuild();const tid=phase<4?'eco-demo-research':phase<6?'eco-demo-review':'eco-demo-write';if(phase===0)taskFlow({kind:'assigned',task_id:tid});if(phase===1)taskFlow({kind:'claimed',task_id:tid});if(phase===2)memoryFlow({taskId:tid,state:'requested'});if(phase===3)memoryFlow({taskId:tid,state:'returned'});if(phase===4)taskFlow({kind:'blocked',task_id:tid});if(phase===5)taskFlow({kind:'claimed',task_id:tid});if(phase===6)taskFlow({kind:'completed',task_id:tid});$('#ecoDemoStep').textContent=['새 요청을 프로젝트로 전달','부서에 일을 나누고 조사 시작','미미르에 회사 정보 요청','정보를 받아 업무에 반영','검토 자료 누락 · 빨간 선으로 표시','막힌 부분을 풀고 다시 진행','업무 완료 · 결과 보고로 연결'][phase]}}
 if(now-lastClock>5000){lastClock=now;if(!demo&&(rawSlack&&isOffline()||pipeline&&Date.now()/1000-pipeline.checked>=40))rebuild()}
}
async function poll(){if(polling||!visible()||!sessionStorage.getItem('hermesDeskToken'))return;polling=true;try{const res=await fetch('/api/ecosystem',{headers:{'X-Desk-Token':sessionStorage.getItem('hermesDeskToken')}});if(!res.ok)throw Error('연결 확인');const data=await res.json();pipeline=data;pipeFailed=false;const previous=sourceCounts;sourceCounts=new Map(data.sources.map(s=>[s.id,s.count]));if(!demo){rebuild();if(previous&&motion&&!isOffline())for(const s of data.sources){if(s.count>(previous.get(s.id)??s.count)&&Date.now()/1000-s.lastAdded<60){const g=groups.find(g=>g.ids.includes(s.id));if(g)flow(G.curve(g.pos,brain,1.3),'data',`${s.name} · 새 자료 ${s.count-previous.get(s.id)}건 미미르에 저장`)}}}memoryTracker.take(data.memoryActivity,!demo&&visible()&&motion&&!isOffline(),Date.now()/1000).forEach(memoryFlow)}catch(e){pipeFailed=true;flows=[];if(!demo)rebuild()}finally{polling=false}}
window.addEventListener('hermes:slack',e=>{rawSlack=e.detail;lastSlack=Date.now();slackFailed=!!rawSlack.errors?.length;if(!demo)rebuild()});window.addEventListener('hermes:slack-error',()=>{slackFailed=true;flows=[];if(!demo)rebuild()});window.addEventListener('hermes:operations',e=>{operations=e.detail;if(!demo)rebuild();const fresh=opTracker.take(operations.events,!demo&&motion&&visible()&&!isOffline(),Date.now()/1000);fresh.forEach(taskFlow)});
function example(){const phase=Math.max(demoPhase,0),p=(rawSlack?.projects||[]).filter(p=>V.place(p)).find(p=>V.place(p).key==='ditalk')||{id:'eco-demo-project',name:'디토크'},roles=['조사·분석','콘텐츠 작성','검토 담당'],ids=['eco-demo-research','eco-demo-write','eco-demo-review'],statuses=phase===6?['done','done','done']:phase===5?['done','done','running']:phase===4?['done','done','blocked']:phase===3?['done','running','todo']:phase>0?['running','todo','todo']:['ready','todo','todo'];const tasks=ids.map((id,i)=>({id,assignee:['opresearch','mktwriter','devreview'][i],roleName:roles[i],title:['회사 자료를 찾아 캠페인 방향 조사','콘텐츠 초안 작성','표현과 자료 검토'][i],shortTitle:['캠페인 방향 조사','콘텐츠 초안 작성','내용 검토'][i],status:statuses[i],parents:i?[{id:ids[i-1],status:statuses[i-1]}]:[],reasonBrief:phase===4&&i===2?'검토할 자료 누락 · 체험 상황':'',result:phase===6?'체험용 결과':'',lastProgressAt:Date.now()/1000}));return {checked:Date.now()/1000,projects:V.places.map(a=>(rawSlack?.projects||[]).find(p=>V.place(p)?.key===a.key)||{id:a.key==='ditalk'?p.id:'eco-demo-'+a.key,name:a.name}),conversations:[{id:'eco-demo-request',summary:'디토크 캠페인 콘텐츠 만들기 · 체험',user:'체험 요청자',reportable:true,projectIds:[p.id],projectNames:[p.name],tasks,attachments:[],state:phase===6?'recorded_done':'working'}],agents:rawSlack?.agents||[{id:'opresearch',group:'운영팀',role:'조사·분석'},{id:'mktwriter',group:'마케팅팀',role:'콘텐츠 작성'},{id:'devreview',group:'개발팀',role:'검토 담당'}],routes:[],errors:[]}}
function demoPipeline(){return {checked:Date.now()/1000,brain:{readable:true,total:groups.length*100,facts:320,recordedSources:groups.length},sources:groups.flatMap(g=>g.ids.map(id=>({id,name:g.name,mark:g.mark,category:'가상 원천',connection:'connected',state:'recent',count:100,lastAdded:Date.now()/1000,note:'가상 데이터 · 체험'}))),jobs:[{id:'memory-collect',name:'자료 수집',state:'ok',at:Date.now()/1000}],memoryActivity:demoPhase>=2?[{id:'eco-demo-memory',taskId:'eco-demo-research',at:Date.now()/1000,state:demoPhase>=3?'returned':'requested'}]:[]}}
function stopDemo(){demo=false;demoPhase=-1;flows=[];history=[];$('#ecoEvents').textContent='실제 새 실행 기록을 기다리는 중';opTracker.reset();memoryTracker.reset();$('#ecoDemoBanner').hidden=true;$('#ecoDemo').textContent='흐름 체험';signature='';home()}
function startDemo(){if(demo)return stopDemo();demo=true;demoStart=performance.now();demoPhase=-1;flows=[];motion=true;document.body.classList.remove('eco-paused');$('#ecoPause').setAttribute('aria-pressed','false');$('#ecoPause').textContent='Ⅱ';$('#ecoDemo').textContent='체험 종료';$('#ecoDemoBanner').hidden=false;signature='';home()}
$('#ecoLabels').addEventListener('pointerover',e=>{const el=e.target.closest('[data-eco-node]');if(el)hover=nodes.find(n=>n.key===el.dataset.ecoNode)});$('#ecoLabels').addEventListener('pointerout',()=>hover=null);
root.addEventListener('click',e=>{const node=e.target.closest('[data-eco-node]'),req=e.target.closest('[data-eco-request]'),report=e.target.closest('[data-eco-report]'),page=e.target.closest('[data-eco-page]');if(node){const n=nodes.find(n=>n.key===node.dataset.ecoNode);if(n)focus(n.type,n.id)}if(req)focus('request',req.dataset.ecoRequest);if(report){if(demo)return signal('체험용 결과 · 실제 업무는 변경되지 않음');window.HermesReport?.openRequest(report.dataset.ecoReport)}if(e.target.closest('[data-eco-catalog]'))focus('sources','all');if(page)document.querySelector(`nav [data-page="${page.dataset.ecoPage}"]`)?.click()});
$('#ecoSources').onclick=()=>focus('sources','all');$('#ecoHome').onclick=home;$('#ecoReset').onclick=home;$('#ecoClose').onclick=home;$('#ecoProblems').onclick=()=>{if(engine)engine.target={angle:.04,zoom:.92,x:0,y:smallLayout?7:8,z:3};problemOnly=!problemOnly;$('#ecoProblems').setAttribute('aria-pressed',problemOnly);selection=problemOnly?{type:'problems'}:null;rebuild()};$('#ecoAllProjects').onclick=()=>focus('projects','all');$('#ecoResults').onclick=()=>focus('results','all');$('#ecoEvidence').onclick=()=>focus('evidence','all');$('#ecoDemo').onclick=startDemo;$('#ecoDemoExit').onclick=stopDemo;$('#ecoPause').onclick=()=>{motion=!motion;flows=[];opTracker.reset();memoryTracker.reset();$('#ecoPause').setAttribute('aria-pressed',!motion);$('#ecoPause').textContent=motion?'Ⅱ':'▶';$('#ecoPause').setAttribute('aria-label',motion?'움직임 멈춤':'움직임 재생');document.body.classList.toggle('eco-paused',!motion);if(demo&&motion)demoStart=performance.now()-Math.max(0,demoPhase)*4800};$('#ecoZoomIn').onclick=()=>{if(engine)engine.target.zoom=Math.min(2.3,engine.target.zoom+.18)};$('#ecoZoomOut').onclick=()=>{if(engine)engine.target.zoom=Math.max(.7,engine.target.zoom-.18)};$('#ecoFullscreen').onclick=()=>{const action=document.fullscreenElement?document.exitFullscreen():root.requestFullscreen?.();action?.catch(()=>signal('창 크기를 넓혀서 전체 화면으로 볼 수 있어요.'))};
function pick(e){if(!engine)return null;const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;for(const n of [...nodes].reverse()){const p=engine.project(...n.pos),radius=n.type==='planet'?30:n.type==='brain'?45:13;if(Math.hypot(x-p.x,y-p.y)<radius)return n}for(const l of links){for(let i=1;i<l.points.length;i+=2){const p=engine.project(...l.points[i]);if(Math.hypot(x-p.x,y-p.y)<6)return {type:l.type,id:l.id}}}return null}
canvas.addEventListener('pointerdown',e=>{if(!engine)return;drag={x:e.clientX,y:e.clientY,angle:engine.target.angle,z:engine.target.z};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!engine)return;if(engine.aim&&motion){const r=canvas.getBoundingClientRect();engine.aim.x=(e.clientX-r.left)/r.width-.5;engine.aim.y=(e.clientY-r.top)/r.height-.5}if(drag){engine.target.angle=drag.angle+(e.clientX-drag.x)*.003;engine.target.z=drag.z+(e.clientY-drag.y)*.025}else{hover=pick(e);canvas.style.cursor=hover?'pointer':'grab'}});canvas.addEventListener('pointerup',e=>{const start=drag;drag=null;if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<5){const n=pick(e);if(n)focus(n.type,n.id)}});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('pointerleave',()=>{hover=null;if(engine?.aim)engine.aim={x:0,y:0}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!root.hidden)home()});document.addEventListener('visibilitychange',()=>{flows=[];opTracker.reset();memoryTracker.reset();if(document.hidden&&demo)stopDemo()});document.querySelectorAll('nav [data-page]').forEach(b=>b.addEventListener('click',()=>{const here=b.dataset.page==='ecosystem';document.body.classList.toggle('ecosystem-mode',here);flows=[];opTracker.reset();memoryTracker.reset();if(!here&&demo)stopDemo();if(here){const latest=window.HermesReport?.snapshot();if(latest){rawSlack=latest;lastSlack=Date.now()}rebuild();poll()}}));canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();engine=null;flows=[];$('#ecoFallback').hidden=false});
window.addEventListener('resize',()=>{layout();signature='';if(!selection)home();else rebuild()});
try{engine=new G.Engine(canvas);if(smallLayout)engine.camera.y=engine.target.y=7;materials();requestAnimationFrame(draw)}catch(e){$('#ecoFallback').hidden=false;$('#ecoDemo').disabled=true}const initial=window.HermesReport?.snapshot();if(initial){rawSlack=initial;lastSlack=Date.now()}rebuild();setInterval(poll,8000);poll();$('#ecoPause').setAttribute('aria-pressed',!motion);document.body.classList.toggle('eco-paused',!motion);
})();
