(()=>{
 const active=new Set(['running','in_progress','claimed']);
 const names={todo:'대기',ready:'배정 대기',running:'작업 중',in_progress:'작업 중',claimed:'착수',blocked:'차단',done:'완료',archived:'보관',in_review:'검수 중',review:'검수 중'};
 const eventNames={created:'업무 접수',assigned:'담당 배정',spawned:'실행 시작',claimed:'업무 인수',completed:'결과 회수',blocked:'도움 요청',crashed:'실행 오류',timed_out:'시간 초과',commented:'진행 메모',review_requested:'검수 요청',unblocked:'차단 해제',attached:'결과물 추가'};
 let current=null,cursor=null,busy=false,selected=null,selectedAgent=null,selectedRequest=null,eventLog=[],routeQueue=[],animating=false,stale=true,preview=false,previewTimers=[];
 const roomRoot=$('#officeRooms'),world=$('.office-world');
 const requestNames={dispatching:'응답·업무 정리 중',working:'작업 중',blocked:'차단',waiting:'대기',complete:'전체 작업 완료',unknown:'작업 연결 확인 필요',no_tasks:'연결된 칸반 작업 없음'};
 function robot(kind=''){return `<div class="bot ${kind}" aria-hidden="true"><i class="bot-head"><b></b></i><i class="bot-body"></i><i class="bot-feet"></i><i class="bot-cargo"></i></div>`}
 function agentState(tasks,profile){if(stale)return 'offline';const live=(current.liveAgents||[]).find(a=>a.profile===profile);if(live?.state==='unknown'||live?.state==='attention')return 'attention';if(live?.state==='working')return 'working';if(tasks.some(t=>t.heartbeatStale||t.progressStale))return 'attention';if(tasks.some(t=>active.has(t.status)))return 'working';if(tasks.some(t=>t.status==='blocked'))return 'blocked';return 'idle'}
 function render(){if(!current)return;$('#officeActivation').hidden=preview||!current.activation?.restartRequired;$('#officeActivation').textContent='보고 복구 코드 적용 대기 · Hermes 재시작 필요. 현재 화면은 실제 작업 기록을 조회 중.';$('#officeRequests').innerHTML=(current.requests||[]).slice(0,12).map(r=>`<button class="office-request" data-request="${esc(r.id)}" aria-pressed="${selectedRequest===r.id}"><b>${esc(r.profile)} · ${esc(requestNames[r.state])}</b><span>${r.done}/${r.total} 완료 · ${esc(dt(r.created_at))}</span></button>`).join('');const recovery=current.recoveredReports||[];$('#officeRecovery').hidden=preview||!recovery.length;$('#officeRecovery summary').textContent='이전 보고 확인 · '+recovery.length+'개 업무';const rk=recovery.map(r=>r.taskId+':'+r.events.length).join('|');if($('#officeRecoveryItems').dataset.key!==rk){$('#officeRecoveryItems').dataset.key=rk;$('#officeRecoveryItems').innerHTML='<p>보고 경로 복구 전 기록. Slack으로 다시 보내거나 업무를 재실행하지 않음.</p>'+recovery.map(r=>`<details class="office-task"><summary><b>${esc(r.title)}</b><small>${esc(r.profile)} · ${r.events.length}개 기록</small></summary>${r.events.map(e=>`<p><b>${esc(eventNames[e.kind]||e.kind)}</b> · ${esc(dt(e.at))}<br>${esc(e.text||'상태 기록')}</p>`).join('')}</details>`).join('')}const tasks=current.tasks,groups=new Map();
  for(const a of (preview?[]:data.agents||[])){if(!groups.has(a.group))groups.set(a.group,[]);groups.get(a.group).push(a)}
  for(const t of tasks){if(!t.assignee||[...groups.values()].some(as=>as.some(a=>a.id===t.assignee)))continue;if(!groups.has(t.group))groups.set(t.group,[]);groups.get(t.group).push({id:t.assignee,role:t.role,group:t.group})}
  const signature=JSON.stringify([tasks.map(t=>[t.id,t.status,t.reason,t.actualModel]),[...groups],current.liveAgents,stale]);
  if(roomRoot.dataset.signature!==signature){roomRoot.dataset.signature=signature;roomRoot.innerHTML=[...groups].map(([group,agents],index)=>{
   const owned=tasks.filter(t=>t.group===group),running=owned.filter(t=>active.has(t.status)).length,blocked=owned.filter(t=>t.status==='blocked').length;
   return `<section class="office-room room-color-${index%6}" data-room="${esc(group)}"><button class="office-room-title" data-department="${esc(group)}"><strong>${esc(group)}</strong><span>${running} 작업 · ${blocked} 차단</span></button><div class="office-desks">${agents.map(a=>{const assigned=owned.filter(t=>t.assignee===a.id&&!['done','archived'].includes(t.status)),state=agentState(assigned,a.id);return `<button class="office-agent ${state}" data-agent="${esc(a.id)}" data-department="${esc(group)}" aria-label="${esc(a.id+' '+a.role)}">${robot()}<span class="desk-surface"></span><strong>${esc(a.id)}</strong><small>${state==='offline'?'상태 미확인':state==='working'?'작업 중':state==='blocked'?'차단 '+assigned.filter(t=>t.status==='blocked').length:state==='attention'?'진행 확인 필요':assigned.length?'대기 '+assigned.length:'대기'}</small></button>`}).join('')}</div><div class="room-current">${running?esc(owned.find(t=>active.has(t.status))?.title):blocked?'멈춘 업무 확인 필요':'새 업무 대기'}</div></section>`}).join('')}
  const running=tasks.filter(t=>active.has(t.status)).length,blocked=tasks.filter(t=>t.status==='blocked').length;
  $('#officeCounts').textContent=`${running} 작업 중 · ${blocked} 차단 · ${tasks.filter(t=>['todo','ready'].includes(t.status)).length} 대기${preview?' · '+tasks.filter(t=>t.status==='done').length+' 완료':''}`;
  const responding=(current.liveAgents||[]).filter(a=>a.state==='working').length;$('#officeCounts').textContent+=responding?' · '+responding+'명 응답 중':'';$('#dispatchState').textContent=stale?'연결 확인 중':responding?`${responding}명 응답·업무 정리 중`:running?`${running}개 업무 진행 확인 중`:'실행 중인 업무 없음';renderDetail();
 }
 function renderDetail(){if(!current)return;const opened=new Set([...document.querySelectorAll('.office-task[open]')].map(e=>e.dataset.task));let ts=current.tasks.filter(t=>(!selected||t.group===selected)&&(!selectedAgent||t.assignee===selectedAgent));if(selectedRequest){const req=(current.requests||[]).find(r=>r.id===selectedRequest);ts=ts.filter(t=>req?.taskIds.includes(t.id))}if($('#officeScope').value==='active')ts=ts.filter(t=>!['done','archived'].includes(t.status));
 $('#officeDetail').innerHTML=`<div class="detail-scope"><b>${esc(selectedAgent||selected||selectedRequest||'전체 부서')}</b><span>${ts.length}개 업무</span>${selected||selectedRequest?'<button class="quiet" id="officeClear">전체 보기</button>':''}</div>`+(ts.length?ts.map(t=>`<details class="office-task" data-task="${esc(t.id)}" ${opened.has(t.id)?'open':''}><summary><span class="office-state state-${esc(t.status)}">${esc(names[t.status]||t.status)}</span><b>${esc(t.title)}</b><small>${esc(t.assignee||'담당 미지정')} · ${esc(t.id)}</small></summary><div><p>${esc(t.reason||'추가 대기 사유 없음')}</p><dl><dt>실제 모델</dt><dd>${esc(t.actualModel||'실행 기록 미확인')} ${esc(t.actualProvider||'')} ${t.actualModel?'· '+esc(t.modelEvidence):''}</dd><dt>마지막 진행</dt><dd>${t.lastProgressAt?esc(dt(t.lastProgressAt)):'기록 없음'}</dd><dt>실행 신호</dt><dd>${t.last_heartbeat_at?esc(dt(t.last_heartbeat_at)):'기록 없음'}</dd><dt>보고</dt><dd>${t.subscriptions.length?t.subscriptions.reduce((n,s)=>n+s.pending,0)+'개 미처리 이벤트 후보':'보고 경로 없음'}</dd></dl>${t.result?`<p class="office-result">${esc(t.result)}</p>`:''}</div></details>`).join(''):'<p class="office-empty">해당 조건의 업무 없음</p>');}
 roomRoot.addEventListener('click',e=>{const b=e.target.closest('[data-department]');if(!b)return;selectedRequest=null;selected=b.dataset.department;selectedAgent=b.dataset.agent||null;renderDetail()});
 $('#officeRequests').addEventListener('click',e=>{const b=e.target.closest('[data-request]');if(!b)return;selectedRequest=selectedRequest===b.dataset.request?null:b.dataset.request;selected=selectedAgent=null;render()});
 $('#officeDetail').addEventListener('click',e=>{if(e.target.id==='officeClear'){selected=selectedAgent=selectedRequest=null;renderDetail()}});$('#officeScope').onchange=renderDetail;
 function routes(events,history){eventLog=[...events.filter(e=>eventNames[e.kind]),...eventLog].sort((a,b)=>b.id-a.id).filter((e,i,arr)=>arr.findIndex(x=>x.id===e.id)===i).slice(0,35);$('#officeEvents').innerHTML=eventLog.map(e=>`<li><span>${esc(eventNames[e.kind])} · ${esc(e.assignee||'담당 미정')}</span><b>${esc(e.title)}</b><time>${esc(dt(e.created_at))}</time></li>`).join('');if(history||$('#office').hidden||document.hidden)return;
 for(const e of events){if(Date.now()/1000-e.created_at>15)continue;if(!['created','assigned','spawned','completed'].includes(e.kind))continue;const task=current.tasks.find(t=>t.id===e.task_id);if(task)routeQueue.push({...e,group:task.group})}playRoute();}
 async function playRoute(){if($('#office').hidden||document.hidden){routeQueue=[];return}if(animating||!routeQueue.length||stale)return;animating=true;world.classList.add('office-moving');const e=routeQueue.shift(),room=[...roomRoot.children].find(r=>r.dataset.room===e.group),layer=$('#officeCouriers');
 if(room){const wr=world.getBoundingClientRect(),rr=room.getBoundingClientRect(),dr=$('.office-dispatch').getBoundingClientRect();const start={x:dr.left-wr.left+dr.width/2-20,y:dr.bottom-wr.top-36},end={x:rr.left-wr.left+rr.width/2-20,y:rr.top-wr.top+18};const returning=e.kind==='completed';const from=returning?end:start,to=returning?start:end;const courier=document.createElement('div');courier.className='office-courier';courier.innerHTML=robot('captain')+`<span>${esc(returning?'결과 회수':'업무 전달')} · ${esc(e.assignee)}</span>`;layer.append(courier);const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;const mid=start.y+50;const animation=courier.animate([{transform:`translate(${from.x}px,${from.y}px)`},{transform:`translate(${from.x}px,${mid}px)`,offset:.2},{transform:`translate(${to.x}px,${mid}px)`,offset:.7},{transform:`translate(${to.x}px,${to.y}px)`}],{duration:reduced?1:2600,easing:'ease-in-out',fill:'forwards'});try{await animation.finished}catch{}courier.remove()}
 world.classList.remove('office-moving');animating=false;playRoute();}
 document.querySelector('[data-page="office"]').addEventListener('click',()=>{render();playRoute();poll()});
 async function poll(){if(busy||!TOKEN||preview)return;busy=true;try{const response=await api('operations'+(cursor===null?'':'?after='+cursor));if(preview)return;current=response;window.dispatchEvent(new CustomEvent('hermes:operations',{detail:response}));stale=false;world.classList.remove('office-stale');$('#officeConnection').textContent='● 연결됨 · '+new Date(response.checked*1000).toLocaleTimeString('ko-KR')+' · 3초 갱신';render();routes(response.events,cursor===null);cursor=response.cursor}catch(e){stale=true;world.classList.add('office-stale');$('#officeConnection').textContent='연결 확인 필요 · '+e.message;render()}finally{busy=false}}
 function stopPreview(){preview=false;$('#officeReplay').hidden=true;previewTimers.forEach(clearTimeout);previewTimers=[];routeQueue=[];document.querySelectorAll('.office-courier').forEach(el=>{el.getAnimations().forEach(a=>a.cancel());el.remove()});world.classList.remove('office-preview');roomRoot.dataset.signature='';cursor=null;eventLog=[];selected=selectedAgent=selectedRequest=null;$('#officePreview').textContent='▶ 움직임 미리보기';poll()}
 $('#officePreview').onclick=()=>{if(preview){stopPreview();return}preview=true;$('#officeReplay').hidden=false;previewTimers=[];routeQueue=[];eventLog=[];selected=selectedAgent=selectedRequest=null;stale=false;world.classList.remove('office-stale');world.classList.add('office-preview');$('#officePreview').textContent='■ 실제 업무로 돌아가기';$('#officeConnection').textContent='미리보기 · 예시 업무 / 실제 명령 전송 없음';
 const now=Date.now()/1000;
 const tasks=[{id:'preview-plan',title:'새 서비스 화면 구성 정리',assignee:'기획 담당',role:'기획',group:'기획팀',status:'todo',reason:'업무 전달 대기',subscriptions:[]},{id:'preview-build',title:'화면 구현과 동작 확인',assignee:'개발 담당',role:'개발',group:'개발팀',status:'todo',reason:'업무 전달 대기',subscriptions:[]}];
 current={checked:now,tasks,requests:[],liveAgents:[],events:[],cursor:0};render();$('#dispatchState').textContent='예시 요청 접수 · 두 부서에 업무 전달';
 function step(delay,index,kind,status,message){previewTimers.push(setTimeout(()=>{if(!preview)return;const t=tasks[index];t.status=status;t.reason=message;t.lastProgressAt=Date.now()/1000;if(status==='done')t.result=message;render();$('#dispatchState').textContent=message;routes([{id:delay,kind,task_id:t.id,assignee:t.assignee,title:t.title,created_at:Date.now()/1000}],false)},delay))}
 step(400,0,'assigned','todo','기획팀에 업무 전달 중');step(3200,0,'claimed','in_progress','기획 담당이 화면 구성을 정리하는 중');step(3600,1,'assigned','todo','개발팀에 업무 전달 중');step(6400,1,'claimed','in_progress','두 부서가 각자 맡은 업무 진행 중');step(10500,0,'completed','done','기획 결과를 헤르메스에게 전달');step(14200,1,'completed','done','개발 결과를 헤르메스에게 전달');previewTimers.push(setTimeout(()=>{$('#dispatchState').textContent='결과 수집 완료 · 예시 업무 2 / 2 완료'},17100));
 };
 $('#officeReplay').onclick=()=>{if(preview)stopPreview();$('#officePreview').click()};
 document.querySelectorAll('nav [data-page]').forEach(b=>b.addEventListener('click',()=>{if(preview&&b.dataset.page!=='office')stopPreview()}));
 setInterval(poll,3000);poll();
})();
